title: Jack Mustonen's Portfolio
description: Personal Portfolio Website
theme: minima
baseurl: "" 
url: "https://jackmustonen.com"
author: Jack Mustonen

# Custom CSS
sass:
  style: compressed

# Include custom CSS
include:
  - assets/css/styles.css
